version: "3.8"
services:
  sanwo:
    container_name: sanwo
    image: sanwo
    restart: always
    volumes: .
    build: .
    ports:
      - "4000:4000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - /var/lib/mongodb:/data/db
      - /var/log/mongodb/mongod.log:/data/log
    ports:
      - "27017:27017"
