version: "3.8"
services:
  sanwo:
    container_name: sanwo
    image: abdulloooh/sanwo
    restart: always
    volumes:
      - /home/abdulloooh/bin/coding/personal/mymoneymydebt_backend:/usr/src/app
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4000:4000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - /var/lib/mongodb:/data/db
      - /var/log/mongodb/mongod.log:/data/log
    ports:
      - "27017:27017"
